### ISSUE TITLE
Add comparison against the nodejs native UUID v4 generator

### ISSUE THREAD

**Issue by micalevisk** [rustq/napi-nanoid#5]
as you've added `uuid`, I would like to know how it performs against [`crypto.randomUUID`](https://nodejs.org/api/crypto.html#cryptorandomuuidoptions) :thinking: 

what do you think?

**Comment by micalevisk** [comment]
nvm, the `uuid.v4()` already uses the native when it is available

See https://github.com/uuidjs/uuid/blob/7ce4e9aaf51ffde8bc7c08fd356e44cfc685573e/src/v4.js#L5-L8

**Comment by meloalright** [comment]
Yeah.. in this benchmark has added uuid.v4

and now the crypto.randomUUID has also been added
